version = 0.1

[default.deploy.parameters]
stack_name = "appointment-booking-app"
resolve_s3 = true
s3_prefix = "appointment-booking-app"
region = "us-east-1"
profile = "evive-sandbox"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
